services:
  app:
    build: .
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: